services:
    backend:
        image: node:24-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: sh -c "npm install && npm run dev"
        ports:
            - '3000:3000'
